# Find the difference: You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
      hashmap = {}
      for ltr in s:
         hashmap[ltr] = hashmap.get(ltr, 0) + 1

      for ltr in t:
          if ltr not in hashmap:
              return ltr
          else:
              hashmap[ltr] -= 1
              if hashmap[ltr] == 0:
                del hashmap[ltr]
